export const GOOGLE_CONFIG = {
  INBOX_FOLDER_ID: process.env.GOOGLE_INBOX_FOLDER_ID || "1NsEMlqn_TUeVenFSWgLU3jEsUCa6LWus",
  PROCESSED_FOLDER_ID: process.env.GOOGLE_PROCESSED_FOLDER_ID || "1AUTWsUq2AS-LC2sgKkSqk1bhEYhI_D-2",
  COACHING_EXAMPLES_FOLDER_ID: process.env.GOOGLE_COACHING_EXAMPLES_FOLDER_ID || "10J6xKMbdDlZrKS6el0qWlnZeurtkLStS",
  
  KNOWLEDGE_BASE_DOC_ID: process.env.GOOGLE_KNOWLEDGE_BASE_DOC_ID || "1NxcQYGHXaVfEGK7Vs5AiOjse8bsRbHBEiwdLsMr0LME",
  SDR_PERSONA_DOC_ID: process.env.GOOGLE_SDR_PERSONA_DOC_ID || "1clt69Puie5CB96ukgjMAVCKDyuSPS5BU-C_JrI-tq3I",
  DAILY_SUMMARY_CRITERIA_DOC_ID: process.env.GOOGLE_DAILY_SUMMARY_CRITERIA_DOC_ID || "1fuaUZ6kLtWtdF39meAxfoktSPvRRzVWcGg5oEq8ygL8",
  LEAD_SCORING_PARAMS_DOC_ID: process.env.GOOGLE_LEAD_SCORING_PARAMS_DOC_ID || "1xERqop5Y9iBNjghbwPF4jNpPKVMW8SlPkJEUnczXL5E",
  
  LEADS_SPREADSHEET_ID: process.env.LEADS_SPREADSHEET_ID || "1dEbs4B7oucHJmA8U0-VehfzQN3Yt54RRs6VQlWNxX2I",
};
